version: '3.4'
services:
  #
  pg13:
    container_name: pg13
    image: 'postgres:13.2-alpine'
    stdin_open: true
    network: pg-net

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - PGPORT=5432
    ports: 
      - 5432:5432

  #
  authpg:
    container_name: authpg
    # image: 'penkong/devref-back-typescript-rest-express-pg-typeorm-Auth'
    build: 
      context: ./server
      network: pg-net 
    restart: always
    stdin_open: true
    depends_on:
      - pg13
    environment:
      - DB=postgres
      - PASSWORD=secret
      - DB_URL=postgresql://root:<PASSWORD>@localhost:5432/devref-ts-express-rest-pg-auth?sslmode=disable
      - PORT=5002
      - CORS=http://localhost:3000
      - JWT_KEY=yhgewy5ehuyrhbe56y65465hyy547u456t34y57uy45ytewth654uy45wy
      - JWT_TTL=365d
    ports: 
      - 5002:5002
