{{- if .Values.openconnect.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.component }}-openconnect
  labels:
    app: {{ .Values.app.name }}
    component: {{ .Values.app.component }}
    environment: {{ .Values.environment }}
type: Opaque
data:
  SERVER: {{ .Values.openconnect.server | b64enc | quote }}
  USER: {{ .Values.openconnect.user | b64enc | quote }}
  PASS: {{ .Values.openconnect.pass | b64enc | quote }}
{{- end }}