apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: { 2:<Size> }
  storageClassName: <name of storage class>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
