apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-depl
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: 'dpage/pgadmin4'
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: 'nazemi.works@gmail.com'
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpg-sec
                  key: pgAdminPass
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-srv
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
