# Default values for climate-electric-reader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rbac:
  serviceAccountName: default

app:
  name: link
  component: climate-electric-reader

image:
  repository: 243771237545.dkr.ecr.eu-west-1.amazonaws.com/link/climate-electric-reader
  # tag: specify at install/upgrade time
  pullPolicy: Always

openconnect:
  # enabled: true
  image:
    repository: 243771237545.dkr.ecr.eu-west-1.amazonaws.com/link/climate-electric-reader-openconnect
    tag: latest
    pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}
